/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSalesRouteImport } from './routes/_protected/sales'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ProtectedPurchasesRouteImport } from './routes/_protected/purchases'
import { Route as ProtectedProductsRouteImport } from './routes/_protected/products'
import { Route as ProtectedIncomeRouteImport } from './routes/_protected/income'
import { Route as ProtectedExpensesRouteImport } from './routes/_protected/expenses'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSalesRoute = ProtectedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPurchasesRoute = ProtectedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProductsRoute = ProtectedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIncomeRoute = ProtectedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpensesRoute = ProtectedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/expenses': typeof ProtectedExpensesRoute
  '/income': typeof ProtectedIncomeRoute
  '/products': typeof ProtectedProductsRoute
  '/purchases': typeof ProtectedPurchasesRoute
  '/reports': typeof ProtectedReportsRoute
  '/sales': typeof ProtectedSalesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/expenses': typeof ProtectedExpensesRoute
  '/income': typeof ProtectedIncomeRoute
  '/products': typeof ProtectedProductsRoute
  '/purchases': typeof ProtectedPurchasesRoute
  '/reports': typeof ProtectedReportsRoute
  '/sales': typeof ProtectedSalesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/expenses': typeof ProtectedExpensesRoute
  '/_protected/income': typeof ProtectedIncomeRoute
  '/_protected/products': typeof ProtectedProductsRoute
  '/_protected/purchases': typeof ProtectedPurchasesRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/sales': typeof ProtectedSalesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/dashboard'
    | '/_protected/expenses'
    | '/_protected/income'
    | '/_protected/products'
    | '/_protected/purchases'
    | '/_protected/reports'
    | '/_protected/sales'
    | '/_protected/settings'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sales': {
      id: '/_protected/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof ProtectedSalesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/purchases': {
      id: '/_protected/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof ProtectedPurchasesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/products': {
      id: '/_protected/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProtectedProductsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/income': {
      id: '/_protected/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof ProtectedIncomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses': {
      id: '/_protected/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ProtectedExpensesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExpensesRoute: typeof ProtectedExpensesRoute
  ProtectedIncomeRoute: typeof ProtectedIncomeRoute
  ProtectedProductsRoute: typeof ProtectedProductsRoute
  ProtectedPurchasesRoute: typeof ProtectedPurchasesRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedSalesRoute: typeof ProtectedSalesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExpensesRoute: ProtectedExpensesRoute,
  ProtectedIncomeRoute: ProtectedIncomeRoute,
  ProtectedProductsRoute: ProtectedProductsRoute,
  ProtectedPurchasesRoute: ProtectedPurchasesRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedSalesRoute: ProtectedSalesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
